### ISSUE TITLE
Support hg38 alignment samples

### ISSUE THREAD

**Issue by methygene** [CompEpigen/methylbert#7]
Hello, @hanyangii @lutsik 

MethylBERT is the fantastic work. However, I noticed that there is currently no pre-training model available for the human genome hg38. I was wondering if it would be possible for you to provide a pre-training hg38 model or share the scripts for generating such a model.

Looking forward to your response.

Best regards

Li

**Comment by hanyangii** [comment]
Dear Li

Thanks a lot for your interest. Although we have a plan to update the tutorial with pre-training as well as provide more pre-trained models with different genomes in future, it is still worth it to try the hg19-pretrained model for hg38-aligned samples. (Assuming you ask for hg38 pre-trained models because your samples are aligned with hg38). 

If you see Figure 3B in our manuscript, we have already evaluated MethylBERT performances with hg19-aligned samples using hg19-pretrained and mm10-pretrained models. The results show that there's no significant difference in terms of AUC. Given that the similarity between hg19 and hg38 must be higher than the similarity between hg19 and mm10, I expect MethylBERT pretrained with hg19 to work for hg38-aligned samples

Kind regards,
Yunhee

**Comment by methygene** [comment]
Thank you for your prompt response. I appreciate your efforts in developing MethylBERT and providing valuable insights. I will continue to follow your work closely and look forward to any updates.

Best regards,
Li
