### ISSUE TITLE
Error in preprocessing training data (command-line)

### ISSUE THREAD

**Issue by edogiuili** [CompEpigen/methylbert#8]
Hi, @hanyangii very interesting tool! I was trying to use it on my .bam files but, after extracting correctly the DMRs:

MethylBERT v0.0.2
Could not find any statistics to sort DMRs
     chr     start       end  CpG    NBL:mu  cfDNA:mu      diff  pval  FDR ctype  dmr_id
0  chr19  35827870  35827913    7  0.035474  0.996667  0.961193     0    0     T       0
1   chr9    299747    299895    8  0.022799  0.982566  0.959766     0    0     T       1
2  chr12  66145926  66145934    4  0.034425  0.982345  0.947920     0    0     T       2
3   chr9    564114    564146    8  0.040699  0.988505  0.947806     0    0     T       3
4   chr5  14441366  14441463    9  0.036063  0.983060  0.946997     0    0     T       4
Number of DMRs to extract sequence reads: 367

I ended up on this error:
`[E::bgzf_read_block] Invalid BGZF header at offset 638937186
[E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes`

It is probably due to samtools, do you have any idea why?

**Comment by hanyangii** [comment]
Hello, @edogiuili 
Thanks a lot for your interest!

Actually the bgzf_read_block error you got is not caused by MethylBERT but by .bam files, as far as I know. It often occurs when the bam file is corrupted. For example, [https://github.com/samtools/samtools/issues/1815](https://github.com/samtools/samtools/issues/1815) has the same error because their file was corrupted by STAR, which is an alignment tool they used. 

According to this [git issue page](https://github.com/samtools/samtools/issues/1811), different versions of library may cause such problems. Maybe you can compare your library versions to my library versions related to alignment.

bio                       1.6.2                    pypi_0    pypi
biopython                 1.81                     pypi_0    pypi
biothings-client          0.3.1                    pypi_0    pypi
pysam                     0.22.0                   pypi_0    pypi
